name: 'scenario-simulator-v2-behavior-plugin-ci-action'
description: 'CI action for behavior plugin in scenario_simulator_v2'
branding:
  icon: "user-check"
  color: "blue"
inputs:
  repository_name:
    description: "repository name of behavior plugin github repository, such as tier4/context_gamma_planner"
    required: true
  repos_path:
    description: relative repos yaml path in your repository
    required: false
    default: dependency.repos
  cmake_args:
    description: "--cmake-args variable in colcon build"
    required: false
    default: -DWITH_INTEGRATION_TEST=ON
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repository_name }}
    - ${{ inputs.repos_path }}
    - ${{ inputs.cmake_args }}