name: test

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    name: A test job for scenario-simulator-v2-behavior-plugin-ci-action
    strategy:
      fail-fast: false
      matrix:
        ros_distro: [foxy, galactic]
    steps:
    - name: Run scenario-simulator-v2-behavior-plugin-ci-action action
      uses: ./
      with:
        repository_name: tier4/context_gamma_planner
        cmake_args: -DWITH_INTEGRATION_TEST=ON -DCMAKE_CXX_FLAGS='-fprofile-arcs -ftest-coverage' -DCMAKE_C_FLAGS='-fprofile-arcs -ftest-coverage'
        ros_distro: ${{ matrix.ros_distro }}
      env:
        GITHUB_TOKEN: ${{ secrets.CLONE_TOKEN }}