name: test

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    name: A test job for scenario-simulator-v2-behavior-plugin-ci-action
    strategy:
      fail-fast: false
      matrix:
        rosdistro: [galactic]
    steps:
    # To use this repository's private action, you must check out the repository
    - uses: actions/checkout@v2
    - name: Run scenario-simulator-v2-behavior-plugin-ci-action test action
      uses: ./
      with:
        repos_yaml: |
          "{\"repositories\": {
            \"context_gamma_planner\": {
              \"type\": \"git\",
              \"url\": \"https://github.com/tier4/context_gamma_planner.git\",
              \"version\": \"master\"}}}"
        cmake_args: -DWITH_INTEGRATION_TEST=ON"
      env:
        GTHUB_TOKEN: ${{ secrets.CLONE_TOKEN }} 